/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_io_nativeio_NativeIO */

#ifndef _Included_org_apache_hadoop_io_nativeio_NativeIO
#define _Included_org_apache_hadoop_io_nativeio_NativeIO
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_hadoop_io_nativeio_NativeIO_O_RDONLY
#define org_apache_hadoop_io_nativeio_NativeIO_O_RDONLY 0L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_WRONLY
#define org_apache_hadoop_io_nativeio_NativeIO_O_WRONLY 1L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_RDWR
#define org_apache_hadoop_io_nativeio_NativeIO_O_RDWR 2L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_CREAT
#define org_apache_hadoop_io_nativeio_NativeIO_O_CREAT 64L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_EXCL
#define org_apache_hadoop_io_nativeio_NativeIO_O_EXCL 128L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_NOCTTY
#define org_apache_hadoop_io_nativeio_NativeIO_O_NOCTTY 256L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_TRUNC
#define org_apache_hadoop_io_nativeio_NativeIO_O_TRUNC 512L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_APPEND
#define org_apache_hadoop_io_nativeio_NativeIO_O_APPEND 1024L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_NONBLOCK
#define org_apache_hadoop_io_nativeio_NativeIO_O_NONBLOCK 2048L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_SYNC
#define org_apache_hadoop_io_nativeio_NativeIO_O_SYNC 4096L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_ASYNC
#define org_apache_hadoop_io_nativeio_NativeIO_O_ASYNC 8192L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_FSYNC
#define org_apache_hadoop_io_nativeio_NativeIO_O_FSYNC 4096L
#undef org_apache_hadoop_io_nativeio_NativeIO_O_NDELAY
#define org_apache_hadoop_io_nativeio_NativeIO_O_NDELAY 2048L
/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    fstat
 * Signature: (Ljava/io/FileDescriptor;)Lorg/apache/hadoop/io/nativeio/NativeIO/Stat;
 */
JNIEXPORT jobject JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_fstat
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    getUIDforFDOwnerforOwner
 * Signature: (Ljava/io/FileDescriptor;)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_getUIDforFDOwnerforOwner
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    getUserName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_getUserName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_initNative
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hadoop_io_nativeio_NativeIO
 * Method:    chmod
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_io_nativeio_NativeIO_chmod
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
